- op: replace
  path: /metadata/name
  value: debora
- op: replace
  path: /spec/source/path
  value: deployment/plat-app-services/debora
- op: replace
  path: /spec/project
  value: plat-app-services